import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { db } from "@/lib/prisma";

const rules = [
  {
    country: "Canada",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: true,
    minAge: 18,
    maxAge: 45,
    requiresDegree: true,
    requiresWorkExperience: true,
    requiresJobOffer: false,
    requiresEnglishTest: true,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "CELPIP", "PTE"],
    minEnglishScore: 6.0,
    estimatedStudyCost: "$15,000 - $25,000 / year",
    estimatedWorkVisaCost: "$155+",
    estimatedMigrationCost: "$1,365+",
    fundsProofAmount: "Varies by program and family size",
    processingTimeStudy: "4 to 12 weeks",
    processingTimeWork: "Varies by stream",
    processingTimeMigration: "6 to 12 months",
    keyDocuments: [
      "Passport",
      "Academic transcripts",
      "Degree certificate",
      "English test result",
      "Proof of funds",
      "CV",
    ],
    commonRefusalReasons: [
      "Weak proof of funds",
      "Low language score",
      "Incomplete documents",
    ],
    notes: "Canada offers both study-first and skilled migration pathways.",
    officialSourceUrl: "https://www.canada.ca",
    lastReviewedAt: new Date(),
  },
  {
    country: "Australia",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: true,
    minAge: 18,
    maxAge: 45,
    requiresDegree: true,
    requiresWorkExperience: true,
    requiresJobOffer: false,
    requiresEnglishTest: true,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "PTE", "TOEFL"],
    minEnglishScore: 6.0,
    estimatedStudyCost: "$20,000 - $45,000 / year",
    estimatedWorkVisaCost: "$1,455+",
    estimatedMigrationCost: "$4,640+",
    fundsProofAmount: "Must show enough funds for tuition and living costs",
    processingTimeStudy: "4 to 10 weeks",
    processingTimeWork: "Varies by visa class",
    processingTimeMigration: "6 to 18 months",
    keyDocuments: [
      "Passport",
      "Degree certificate",
      "Employment references",
      "English test result",
      "Proof of funds",
    ],
    commonRefusalReasons: [
      "Low points score",
      "Insufficient funds",
      "Weak employment evidence",
    ],
    notes: "Australia uses a points-based system for major migration pathways.",
    officialSourceUrl: "https://immi.homeaffairs.gov.au",
    lastReviewedAt: new Date(),
  },
  {
    country: "UK",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: false,
    minAge: 18,
    maxAge: null,
    requiresDegree: false,
    requiresWorkExperience: false,
    requiresJobOffer: true,
    requiresEnglishTest: true,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "PTE", "TOEFL"],
    minEnglishScore: 5.5,
    estimatedStudyCost: "$15,000 - $30,000 / year",
    estimatedWorkVisaCost: "$800+",
    estimatedMigrationCost: null,
    fundsProofAmount: "Depends on route and stay length",
    processingTimeStudy: "3 to 8 weeks",
    processingTimeWork: "3 to 8 weeks",
    processingTimeMigration: null,
    keyDocuments: [
      "Passport",
      "CAS or sponsorship documents",
      "Bank statement",
      "English proof",
    ],
    commonRefusalReasons: [
      "Missing sponsorship evidence",
      "Weak funds proof",
      "Document mismatch",
    ],
    notes: "UK work pathways commonly require sponsorship.",
    officialSourceUrl: "https://www.gov.uk",
    lastReviewedAt: new Date(),
  },
  {
    country: "Germany",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: true,
    minAge: 18,
    maxAge: null,
    requiresDegree: true,
    requiresWorkExperience: false,
    requiresJobOffer: false,
    requiresEnglishTest: false,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "TOEFL"],
    minEnglishScore: 6.0,
    estimatedStudyCost: "Low tuition, living cost still applies",
    estimatedWorkVisaCost: "$75 - $150+",
    estimatedMigrationCost: "$75 - $150+",
    fundsProofAmount: "Blocked account often required for study routes",
    processingTimeStudy: "6 to 12 weeks",
    processingTimeWork: "4 to 12 weeks",
    processingTimeMigration: "Varies",
    keyDocuments: [
      "Passport",
      "Academic documents",
      "Proof of accommodation",
      "Proof of funds",
      "CV",
    ],
    commonRefusalReasons: [
      "Weak finances",
      "Missing translated documents",
      "Unclear purpose of stay",
    ],
    notes: "Germany can be strong for study and opportunity-card style routes.",
    officialSourceUrl: "https://www.make-it-in-germany.com",
    lastReviewedAt: new Date(),
  },
  {
    country: "Ireland",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: false,
    minAge: 18,
    maxAge: null,
    requiresDegree: true,
    requiresWorkExperience: false,
    requiresJobOffer: true,
    requiresEnglishTest: true,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "TOEFL", "PTE"],
    minEnglishScore: 6.0,
    estimatedStudyCost: "$10,000 - $25,000 / year",
    estimatedWorkVisaCost: "$1,000+",
    estimatedMigrationCost: null,
    fundsProofAmount: "Study applicants usually need financial evidence",
    processingTimeStudy: "4 to 8 weeks",
    processingTimeWork: "6 to 12 weeks",
    processingTimeMigration: null,
    keyDocuments: [
      "Passport",
      "Admission or permit documents",
      "Proof of funds",
      "English score",
    ],
    commonRefusalReasons: [
      "Weak funds proof",
      "Incomplete study documents",
      "No eligible work permit basis",
    ],
    notes: "Ireland is often strongest for study and critical-skills employment routes.",
    officialSourceUrl: "https://www.irishimmigration.ie",
    lastReviewedAt: new Date(),
  },
  {
    country: "Netherlands",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: false,
    minAge: 18,
    maxAge: null,
    requiresDegree: true,
    requiresWorkExperience: false,
    requiresJobOffer: true,
    requiresEnglishTest: true,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "TOEFL", "PTE"],
    minEnglishScore: 6.0,
    estimatedStudyCost: "$8,000 - $20,000 / year",
    estimatedWorkVisaCost: "$350+",
    estimatedMigrationCost: null,
    fundsProofAmount: "Applicants often need proof of tuition and living costs",
    processingTimeStudy: "2 to 8 weeks",
    processingTimeWork: "2 to 12 weeks",
    processingTimeMigration: null,
    keyDocuments: [
      "Passport",
      "Academic documents",
      "Proof of admission or employment",
      "Proof of funds",
      "English score",
    ],
    commonRefusalReasons: [
      "Insufficient funds",
      "Weak admission or employment basis",
      "Incomplete documentation",
    ],
    notes: "The Netherlands is attractive for study and highly-skilled migrant employment pathways.",
    officialSourceUrl: "https://ind.nl",
    lastReviewedAt: new Date(),
  },
  {
    country: "Sweden",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: false,
    minAge: 18,
    maxAge: null,
    requiresDegree: true,
    requiresWorkExperience: false,
    requiresJobOffer: true,
    requiresEnglishTest: true,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "TOEFL", "PTE"],
    minEnglishScore: 6.0,
    estimatedStudyCost: "$9,000 - $18,000 / year",
    estimatedWorkVisaCost: "$200+",
    estimatedMigrationCost: null,
    fundsProofAmount: "Students usually need to show maintenance funds",
    processingTimeStudy: "1 to 3 months",
    processingTimeWork: "1 to 4 months",
    processingTimeMigration: null,
    keyDocuments: [
      "Passport",
      "Admission or employment documents",
      "Bank statements",
      "English test result",
      "Insurance or residence documents",
    ],
    commonRefusalReasons: [
      "Insufficient maintenance funds",
      "Weak job or study basis",
      "Incomplete supporting evidence",
    ],
    notes: "Sweden can be a strong route for study and employer-sponsored work permits.",
    officialSourceUrl: "https://www.migrationsverket.se",
    lastReviewedAt: new Date(),
  },
  {
    country: "New Zealand",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: true,
    minAge: 18,
    maxAge: 55,
    requiresDegree: true,
    requiresWorkExperience: true,
    requiresJobOffer: false,
    requiresEnglishTest: true,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "PTE", "TOEFL"],
    minEnglishScore: 6.0,
    estimatedStudyCost: "$12,000 - $25,000 / year",
    estimatedWorkVisaCost: "$700+",
    estimatedMigrationCost: "$2,000+",
    fundsProofAmount: "Must usually show living and study support funds",
    processingTimeStudy: "4 to 8 weeks",
    processingTimeWork: "1 to 3 months",
    processingTimeMigration: "6 to 12 months",
    keyDocuments: [
      "Passport",
      "Academic documents",
      "Work references",
      "English test result",
      "Proof of funds",
    ],
    commonRefusalReasons: [
      "Low English score",
      "Weak funds evidence",
      "Insufficient work history",
    ],
    notes: "New Zealand can suit both study and skilled residence planning.",
    officialSourceUrl: "https://www.immigration.govt.nz",
    lastReviewedAt: new Date(),
  },
  {
    country: "Finland",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: false,
    minAge: 18,
    maxAge: null,
    requiresDegree: true,
    requiresWorkExperience: false,
    requiresJobOffer: true,
    requiresEnglishTest: true,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "TOEFL", "PTE"],
    minEnglishScore: 6.0,
    estimatedStudyCost: "$6,000 - $18,000 / year",
    estimatedWorkVisaCost: "$500+",
    estimatedMigrationCost: null,
    fundsProofAmount: "Students usually need proof of living expenses and tuition support",
    processingTimeStudy: "1 to 3 months",
    processingTimeWork: "1 to 4 months",
    processingTimeMigration: null,
    keyDocuments: [
      "Passport",
      "Admission or job documents",
      "Proof of income or funds",
      "Academic records",
      "English result",
    ],
    commonRefusalReasons: [
      "Weak financial proof",
      "Incomplete admission or employment documents",
      "Insufficient eligibility evidence",
    ],
    notes: "Finland is growing in appeal for study and employment-based relocation.",
    officialSourceUrl: "https://migri.fi",
    lastReviewedAt: new Date(),
  },
  {
    country: "USA",
    studyAvailable: true,
    workAvailable: true,
    migrationAvailable: false,
    minAge: 18,
    maxAge: null,
    requiresDegree: true,
    requiresWorkExperience: true,
    requiresJobOffer: true,
    requiresEnglishTest: true,
    requiresFundsProof: true,
    acceptedEnglishTests: ["IELTS", "TOEFL", "PTE"],
    minEnglishScore: 6.5,
    estimatedStudyCost: "$20,000 - $50,000+ / year",
    estimatedWorkVisaCost: "$460+",
    estimatedMigrationCost: null,
    fundsProofAmount: "Students must often show strong financial capacity",
    processingTimeStudy: "Varies by embassy and season",
    processingTimeWork: "Varies by petition and category",
    processingTimeMigration: null,
    keyDocuments: [
      "Passport",
      "DS-160 and visa records",
      "SEVIS or petition documents",
      "Proof of funds",
      "Academic and employment records",
    ],
    commonRefusalReasons: [
      "Weak ties or credibility concerns",
      "Insufficient funds",
      "Incomplete or inconsistent documentation",
    ],
    notes: "The USA is strong for study and employer-sponsored work routes, but highly document-sensitive.",
    officialSourceUrl: "https://travel.state.gov",
    lastReviewedAt: new Date(),
  },
];

export async function POST() {
  try {
    const session = await auth();

    const adminEmails =
      process.env.ADMIN_EMAILS?.split(",").map((e) => e.trim()) || [];

    if (!session?.user?.email) {
      return NextResponse.json({ error: "Not logged in" }, { status: 401 });
    }

    if (!adminEmails.includes(session.user.email)) {
      return NextResponse.json(
        {
          error: `Unauthorized: ${session.user.email} is not in ADMIN_EMAILS`,
        },
        { status: 401 }
      );
    }

    for (const rule of rules) {
      await db.countryRule.upsert({
        where: { country: rule.country },
        update: rule,
        create: rule,
      });
    }

    const count = await db.countryRule.count();

    return NextResponse.json({
      success: true,
      count,
      message: `Seeded ${count} country rules`,
    });
  } catch (error: any) {
    console.error(error);
    return NextResponse.json(
      { error: error?.message || "Failed to seed rules" },
      { status: 500 }
    );
  }
}